### ISSUE TITLE
text on button

### ISSUE THREAD

**Issue by keithwhyman** [ArtemkaKun/wmr-usb-controller#1]
This is an incredibly small issue, but the button always says "Disable WMR device" and seems to be either blue or white.
What it not be possible to change the text to "Enable WMR device" when it is turned off?

thanks

**Comment by ArtemkaKun** [comment]
Hi. I fully agree with this. I will fix that asap

**Comment by keithwhyman** [comment]
Excellent, now that is a prompt answer :)
